In [2]:
l1=['sandy','kamal','karthik','viji']

In [7]:
for i in l1:
    print(i)

sandy
kamal
karthik
viji


In [9]:
x=()

In [17]:
l2=[]
for i in range (1,11):
    l2.append(i)
l2=tuple(l2)

In [20]:
l2

(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)

In [22]:
type(l2)

tuple

In [24]:
x=[(1,2),(3,4),(5,6)]

In [26]:
x

[(1, 2), (3, 4), (5, 6)]

In [28]:
for i,j in x:
    print(i,'+',j,'=',i+j)

1 + 2 = 3
3 + 4 = 7
5 + 6 = 11


In [34]:
for i in range (1,11):
    print(i,'x','2','=',i*2)
 

1 x 2 = 2
2 x 2 = 4
3 x 2 = 6
4 x 2 = 8
5 x 2 = 10
6 x 2 = 12
7 x 2 = 14
8 x 2 = 16
9 x 2 = 18
10 x 2 = 20


In [41]:
Count=eval(input('Enter the limit :'))
table=eval(input('Enter the table no :'))
for i in range(1,Count):
    print(i,'X',table,'=',i*table)

Enter the limit :16
Enter the table no :3
1 X 3 = 3
2 X 3 = 6
3 X 3 = 9
4 X 3 = 12
5 X 3 = 15
6 X 3 = 18
7 X 3 = 21
8 X 3 = 24
9 X 3 = 27
10 X 3 = 30
11 X 3 = 33
12 X 3 = 36
13 X 3 = 39
14 X 3 = 42
15 X 3 = 45


In [43]:
for i in range (5):
    print('Sandy'*i)


Sandy
SandySandy
SandySandySandy
SandySandySandySandy


In [45]:
import numpy as np

In [47]:
x=np.random.randint(10,size=10)
y=np.random.randint(10,size=10)

In [49]:
x

array([9, 9, 1, 6, 9, 1, 6, 0, 3, 3])

In [51]:
y

array([5, 2, 4, 1, 5, 9, 7, 3, 0, 7])

In [53]:
x;y

array([5, 2, 4, 1, 5, 9, 7, 3, 0, 7])

In [55]:
for i in x:
    print(i)

9
9
1
6
9
1
6
0
3
3


In [63]:
b= [i for i in zip(x,y)]


In [65]:
b

[(9, 5),
 (9, 2),
 (1, 4),
 (6, 1),
 (9, 5),
 (1, 9),
 (6, 7),
 (0, 3),
 (3, 0),
 (3, 7)]

In [67]:
type(b)

list

In [5]:
import os

In [6]:
os.getcwd()

'C:\\Users\\kamal'

In [7]:
p="E:\Python"

In [8]:
os.chdir(p)

In [10]:
import pandas as pd

In [11]:
df=pd.read_csv('admit.csv')

In [12]:
df

GRE  TOEFL  Univ_Rating  SOP  LOR  CGPA  Research  Admit
0    337    118            4  4.5  4.5  9.65         1      1
1    324    107            4  4.0  4.5  8.87         1      1
2    316    104            3  3.0  3.5  8.00         1      1
3    322    110            3  3.5  2.5  8.67         1      1
4    314    103            2  2.0  3.0  8.21         0      0
..   ...    ...          ...  ...  ...   ...       ...    ...
395  324    110            3  3.5  3.5  9.04         1      1
396  325    107            3  3.0  3.5  9.11         1      1
397  330    116            4  5.0  4.5  9.45         1      1
398  312    103            3  3.5  4.0  8.78         0      0
399  333    117            4  5.0  4.0  9.66         1      1

[400 rows x 8 columns]

In [83]:
df.head()

GRE  TOEFL  Univ_Rating  SOP  LOR  CGPA  Research  Admit
0  337    118            4  4.5  4.5  9.65         1      1
1  324    107            4  4.0  4.5  8.87         1      1
2  316    104            3  3.0  3.5  8.00         1      1
3  322    110            3  3.5  2.5  8.67         1      1
4  314    103            2  2.0  3.0  8.21         0      0

In [85]:
for val in df:
    print (val)

GRE
TOEFL
Univ_Rating
SOP
LOR
CGPA
Research
Admit


In [87]:
for val in df.values:
    print (val)

[337.   118.     4.     4.5    4.5    9.65   1.     1.  ]
[324.   107.     4.     4.     4.5    8.87   1.     1.  ]
[316.  104.    3.    3.    3.5   8.    1.    1. ]
[322.   110.     3.     3.5    2.5    8.67   1.     1.  ]
[314.   103.     2.     2.     3.     8.21   0.     0.  ]
[330.   115.     5.     4.5    3.     9.34   1.     1.  ]
[321.  109.    3.    3.    4.    8.2   1.    1. ]
[308.  101.    2.    3.    4.    7.9   0.    0. ]
[302.  102.    1.    2.    1.5   8.    0.    0. ]
[323.  108.    3.    3.5   3.    8.6   0.    0. ]
[325.  106.    3.    3.5   4.    8.4   1.    0. ]
[327.  111.    4.    4.    4.5   9.    1.    1. ]
[328.  112.    4.    4.    4.5   9.1   1.    1. ]
[307. 109.   3.   4.   3.   8.   1.   0.]
[311.  104.    3.    3.5   2.    8.2   1.    0. ]
[314.  105.    3.    3.5   2.5   8.3   0.    0. ]
[317.  107.    3.    4.    3.    8.7   0.    0. ]
[319. 106.   3.   4.   3.   8.   1.   0.]
[318.  110.    3.    4.    3.    8.8   0.    0. ]
[303.  102.    3.    3.5  

In [89]:
df['GRE']

0      337
1      324
2      316
3      322
4      314
      ... 
395    324
396    325
397    330
398    312
399    333
Name: GRE, Length: 400, dtype: int64

In [91]:
li=df['GRE']

In [93]:
type(li)

pandas.core.series.Series

In [14]:
GRE=[]
for val in df.GRE.values:
    GRE.append(val)
    


In [17]:
GRE

[337,
 324,
 316,
 322,
 314,
 330,
 321,
 308,
 302,
 323,
 325,
 327,
 328,
 307,
 311,
 314,
 317,
 319,
 318,
 303,
 312,
 325,
 328,
 334,
 336,
 340,
 322,
 298,
 295,
 310,
 300,
 327,
 338,
 340,
 331,
 320,
 299,
 300,
 304,
 307,
 308,
 316,
 313,
 332,
 326,
 322,
 329,
 339,
 321,
 327,
 313,
 312,
 334,
 324,
 322,
 320,
 316,
 298,
 300,
 311,
 309,
 307,
 304,
 315,
 325,
 325,
 327,
 316,
 318,
 328,
 332,
 336,
 321,
 314,
 314,
 329,
 327,
 301,
 296,
 294,
 312,
 340,
 320,
 322,
 340,
 319,
 315,
 317,
 314,
 316,
 318,
 299,
 298,
 301,
 303,
 304,
 306,
 331,
 332,
 323,
 322,
 312,
 314,
 317,
 326,
 316,
 329,
 338,
 331,
 304,
 305,
 321,
 301,
 320,
 311,
 310,
 299,
 290,
 296,
 327,
 335,
 334,
 310,
 308,
 301,
 300,
 323,
 319,
 326,
 333,
 339,
 303,
 309,
 323,
 333,
 314,
 312,
 316,
 326,
 318,
 329,
 332,
 331,
 340,
 325,
 320,
 315,
 326,
 339,
 311,
 334,
 332,
 321,
 324,
 326,
 312,
 315,
 309,
 306,
 297,
 315,
 298,
 318,
 317,
 329,
 322,
 302

In [19]:
type(GRE)

list

In [22]:
SOP=list(i for i in df['SOP'])
print(SOP)

[4.5, 4.0, 3.0, 3.5, 2.0, 4.5, 3.0, 3.0, 2.0, 3.5, 3.5, 4.0, 4.0, 4.0, 3.5, 3.5, 4.0, 4.0, 4.0, 3.5, 3.0, 3.0, 5.0, 5.0, 4.0, 4.5, 4.5, 1.5, 2.0, 1.5, 3.0, 4.0, 3.0, 4.0, 4.0, 5.0, 4.0, 1.0, 3.0, 4.0, 3.5, 2.5, 2.5, 4.5, 4.5, 5.0, 4.0, 4.5, 3.5, 3.0, 2.5, 1.5, 4.0, 4.0, 3.0, 3.0, 2.0, 4.0, 3.0, 2.0, 3.0, 4.0, 3.0, 4.0, 3.0, 3.5, 3.0, 3.5, 3.5, 4.5, 5.0, 5.0, 5.0, 4.5, 3.0, 2.0, 3.0, 3.0, 3.0, 1.5, 2.0, 5.0, 5.0, 4.0, 4.5, 4.5, 4.5, 3.5, 4.5, 4.5, 4.0, 5.0, 4.0, 3.0, 2.0, 1.5, 3.0, 4.0, 5.0, 4.0, 3.5, 2.5, 4.0, 4.5, 3.5, 4.0, 4.5, 3.5, 5.0, 5.0, 3.0, 4.0, 3.5, 4.0, 3.5, 4.5, 4.0, 2.0, 3.0, 3.0, 5.0, 4.5, 1.5, 3.5, 2.5, 2.0, 4.0, 2.5, 3.5, 5.0, 4.0, 5.0, 3.5, 4.0, 4.0, 3.5, 5.0, 1.5, 4.5, 3.5, 4.0, 4.5, 4.0, 4.5, 3.0, 2.0, 2.0, 3.0, 4.0, 3.5, 4.0, 5.0, 5.0, 3.0, 3.0, 3.0, 2.0, 2.0, 2.0, 1.5, 1.5, 1.5, 3.0, 3.5, 4.5, 4.5, 3.5, 2.0, 2.0, 2.5, 2.5, 4.0, 4.0, 4.0, 4.0, 4.5, 4.5, 3.5, 2.5, 3.0, 3.5, 2.5, 3.0, 4.0, 2.5, 4.5, 3.5, 4.5, 4.5, 5.0, 4.5, 4.0, 4.5, 4.5, 3.5, 3.0, 3.0, 3.5, 4.5, 4.0,

In [24]:
for label,val in df.iterrows():
    print(label)
    print(val)

0
GRE            337.00
TOEFL          118.00
Univ_Rating      4.00
SOP              4.50
LOR              4.50
CGPA             9.65
Research         1.00
Admit            1.00
Name: 0, dtype: float64
1
GRE            324.00
TOEFL          107.00
Univ_Rating      4.00
SOP              4.00
LOR              4.50
CGPA             8.87
Research         1.00
Admit            1.00
Name: 1, dtype: float64
2
GRE            316.0
TOEFL          104.0
Univ_Rating      3.0
SOP              3.0
LOR              3.5
CGPA             8.0
Research         1.0
Admit            1.0
Name: 2, dtype: float64
3
GRE            322.00
TOEFL          110.00
Univ_Rating      3.00
SOP              3.50
LOR              2.50
CGPA             8.67
Research         1.00
Admit            1.00
Name: 3, dtype: float64
4
GRE            314.00
TOEFL          103.00
Univ_Rating      2.00
SOP              2.00
LOR              3.00
CGPA             8.21
Research         0.00
Admit            0.00
Name: 4, dtype: float6

In [35]:
new=[val for val in df.iterrows()]
print(new[0])

(0, GRE            337.00
TOEFL          118.00
Univ_Rating      4.00
SOP              4.50
LOR              4.50
CGPA             9.65
Research         1.00
Admit            1.00
Name: 0, dtype: float64)


In [37]:
type(new)

list

In [39]:
for i in range(1,11):
    count = i+1
print(i)

10


In [41]:
for i in range(1,11):
    count = i+1
print(count)

11


In [53]:
for i in range(1,11):
    count = (i+(i*i))/2
print(count)

55.0


In [56]:
count=0
for a in range(1,11):
    count=count+a
print (count)

55


In [58]:
count=0
for a in range(1,11):
    count=count+a
AM= count/10
print (AM)

5.5


In [63]:
df.GRE.values

array([337, 324, 316, 322, 314, 330, 321, 308, 302, 323, 325, 327, 328,
       307, 311, 314, 317, 319, 318, 303, 312, 325, 328, 334, 336, 340,
       322, 298, 295, 310, 300, 327, 338, 340, 331, 320, 299, 300, 304,
       307, 308, 316, 313, 332, 326, 322, 329, 339, 321, 327, 313, 312,
       334, 324, 322, 320, 316, 298, 300, 311, 309, 307, 304, 315, 325,
       325, 327, 316, 318, 328, 332, 336, 321, 314, 314, 329, 327, 301,
       296, 294, 312, 340, 320, 322, 340, 319, 315, 317, 314, 316, 318,
       299, 298, 301, 303, 304, 306, 331, 332, 323, 322, 312, 314, 317,
       326, 316, 329, 338, 331, 304, 305, 321, 301, 320, 311, 310, 299,
       290, 296, 327, 335, 334, 310, 308, 301, 300, 323, 319, 326, 333,
       339, 303, 309, 323, 333, 314, 312, 316, 326, 318, 329, 332, 331,
       340, 325, 320, 315, 326, 339, 311, 334, 332, 321, 324, 326, 312,
       315, 309, 306, 297, 315, 298, 318, 317, 329, 322, 302, 313, 293,
       311, 312, 334, 322, 323, 321, 320, 329, 319, 309, 307, 30

In [64]:
GRE = list(i for i in df['GRE'])
n=list([i for i in GRE])
print(len(n))
c=0
for m in GRE:
    c=(c+m)
    avg=c/len(n)
print(avg)
ss=0
for gre in GRE:
    ss=ss+((gre-avg)**2)
print(ss/(len(n)-1))

400
316.8075
131.6445551378446
